# Generated by Django 3.1.2 on 2020-11-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_auto_20201130_2005'),
        ('setting', '0002_auto_20201130_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('barcode', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('supplier_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.supplier')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.uom')),
                ('warehouse_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.warehouse')),
            ],
            options={
                'db_table': 'input',
            },
        ),
    ]
