# Generated by Django 3.1.2 on 2020-12-15 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_delete_user'),
        ('input', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='barcode',
        ),
        migrations.AlterField(
            model_name='input',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.category'),
        ),
        migrations.AlterField(
            model_name='input',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.uom'),
        ),
    ]
