# Generated by Django 3.1.2 on 2020-12-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_auto_20201215_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
