# Generated by Django 3.1.2 on 2020-12-17 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_delete_user'),
        ('input', '0004_auto_20201216_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.uom'),
        ),
    ]
