# Generated by Django 3.1.2 on 2020-11-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('purchase_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('barcode', models.CharField(max_length=255)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.category')),
                ('supplier_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.supplier')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.uom')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
