# Generated by Django 3.1.2 on 2020-12-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20201202_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='static/logo.png', null=True, upload_to=''),
        ),
    ]
