# Generated by Django 3.1.2 on 2020-12-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20201130_1940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
