# Generated by Django 3.1.2 on 2020-12-16 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting', '0003_delete_user'),
        ('product', '0013_auto_20201215_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.category')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('supplier_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.supplier')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.uom')),
                ('warehouse_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.warehouse')),
            ],
            options={
                'db_table': 'retur',
            },
        ),
    ]
